# Render.com Deployment Config - Optimized for 30s Timeout
# Place this file in root directory as "render.yaml"

services:
  - type: web
    name: tienphong-news-ultra-fast
    env: python
    plan: free
    region: singapore  # Closest to Vietnam
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 25 --keep-alive 2 --max-requests 100 --max-requests-jitter 10 --preload --workers 1 --threads 2 --worker-class sync --worker-connections 50
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_VERSION
        value: latest
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 1
    # Environment variables (set these in Render dashboard)
    # GEMINI_API_KEY: your_api_key_here
    # SECRET_KEY: your_secret_key_here
